// Product list with proper URLs only
const products = [
    { name: "10 ft Table Cover Silver", url: "https://snookercart.com/buy-product/ols/products/10-ft-table-cover-silver-0e77ae" },
    { name: "12 ft Table Cover Silver", url: "https://snookercart.com/buy-product/ols/products/12-ft-table-cover-silver-e32bb2" },
    { name: "15 Panels LED Set", url: "https://snookercart.com/buy-product/ols/products/15-panels-led-set-c9f105" },
    { name: "1G Cue Ball", url: "https://snookercart.com/buy-product/ols/products/1g-cue-ball-2fd975" },
    { name: "1G Super Pro Aramith Snooker Ballset 52.4mm", url: "https://snookercart.com/buy-product/ols/products/1g-super-pro-aramith-snooker-ballset-52-4mm-91f68d" },
    { name: "1G Super Pro Aramith Snooker Ballset 52.4mm Used", url: "https://snookercart.com/buy-product/ols/products/1g-super-pro-aramith-snooker-ballset-52-4mm-used-d2118f" },
    { name: "20 Holes Cue Stand", url: "https://snookercart.com/buy-product/ols/products/20-holes-cue-stand-916c9c" },
    { name: "6 Panel LED Set", url: "https://snookercart.com/buy-product/ols/products/6-panel-led-set-05618d" },
    { name: "7 Holes Cue Stand", url: "https://snookercart.com/buy-product/ols/products/7-holes-cue-stand-5ab7ba" },
    { name: "8 Ball pool frame wooden Large Balls", url: "https://snookercart.com/buy-product/ols/products/8-ball-pool-frame-wooden-large-balls-4e5ab1" },
    { name: "8 Holes Cue Stand", url: "https://snookercart.com/buy-product/ols/products/8-holes-cue-stand-4737c7" },
    { name: "9 Ball pool frame wooden", url: "https://snookercart.com/buy-product/ols/products/9-ball-pool-frame-wooden-270ed7" },
    { name: "9 ft Table Cover Silver", url: "https://snookercart.com/buy-product/ols/products/9-ft-table-cover-silver-0f2690" },
    { name: "ADR Cutter", url: "https://snookercart.com/buy-product/ols/products/adr-cutter-ddd941" },
    { name: "Adr Pouch Single Black", url: "https://snookercart.com/buy-product/ols/products/adr-pouch-single-black-b54e95" },
    { name: "ADR Tip 10mm Grey", url: "https://snookercart.com/buy-product/ols/products/adr-tip-10mm-grey-c50a7f" },
    { name: "ADR Tip 10mm MJW", url: "https://snookercart.com/buy-product/ols/products/adr-tip-10mm-mjw-76a148" },
    { name: "ADR Tip Med 10mm", url: "https://snookercart.com/buy-product/ols/products/adr-tip-med-10mm-e35de2" },
    { name: "ADR Tip Soft 10mm", url: "https://snookercart.com/buy-product/ols/products/adr-tip-soft-10mm-6be832" },
    { name: "ADR Tip Super Soft 10mm", url: "https://snookercart.com/buy-product/ols/products/adr-tip-super-soft-10mm-bd7917" },
    { name: "Aluminium Case Black 1 Piece - New", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-black-1-piece-new-12abfc" },
    { name: "Aluminium Case Black 3/4 - Silk", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-black-3-4-silk-7ea3c7" },
    { name: "Aluminium Case Blue 1 Piece - New", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-blue-1-piece-new-0e9653" },
    { name: "Aluminium Case For 3 Cues Black 1 Piece", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-for-3-cues-black-1-piece-5c2181" },
    { name: "Aluminium Case Golden 1 Piece - New", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-golden-1-piece-new-ef4f86" },
    { name: "Aluminium Case Golden 1 Piece- Silk", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-golden-1-piece-silk-2b60ee" },
    { name: "Aluminium Case Golden 3/4 - Silk", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-golden-3-4-silk-a3c831" },
    { name: "Aluminium Case Red 1 Piece - New", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-red-1-piece-new-347e7c" },
    { name: "Aluminium Case Red 1 Piece - Silk", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-red-1-piece-silk-909062" },
    { name: "Aluminium Case Red 3/4 Silk Metal Cap", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-red-3-4-silk-metal-cap-8935ab" },
    { name: "Aluminium Case Silver 1 Piece - New", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-silver-1-piece-new-dfe35a" },
    { name: "Aluminium Case Silver 3/4", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-silver-3-4-50287b" },
    { name: "Aluminium Case Silver 3/4 - Silk", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-silver-3-4-silk-3c34e1" },
    { name: "Aluminium Case Sky Blue 1 Piece - Silk", url: "https://snookercart.com/buy-product/ols/products/aluminium-case-sky-blue-1-piece-silk-a6446b" },
    { name: "Aluminium Omin Case 3/4", url: "https://snookercart.com/buy-product/ols/products/aluminium-omin-case-3-4-f4c576" },
    { name: "Aluminium Pocket Railing Pack of 6 Black-Golden - Large", url: "https://snookercart.com/buy-product/ols/products/aluminium-pocket-railing-pack-of-6-black-golden-large-47f1a2" },
    { name: "Aluminium Pocket Railing Pack of 6 Black-Golden - Small", url: "https://snookercart.com/buy-product/ols/products/aluminium-pocket-railing-pack-of-6-black-golden-small-1c437c" },
    { name: "American Club Pool Cue 3 Piece", url: "https://snookercart.com/buy-product/ols/products/american-club-pool-cue-3-piece-c1561a" },
    { name: "American Pool Cue 1/2", url: "https://snookercart.com/buy-product/ols/products/american-pool-cue-1-2-6f1f53" },
    { name: "American Pool Cue 3 Piece", url: "https://snookercart.com/buy-product/ols/products/american-pool-cue-3-piece-d021d1" },
    { name: "American Pool Table Pocket Pack of 6 Black", url: "https://snookercart.com/buy-product/ols/products/american-pool-table-pocket-pack-of-6-black-6b8071" },
    { name: "Andy 600 4.5X9 Blue", url: "https://snookercart.com/buy-product/ols/products/andy-600-4-5x9-blue-191305" },
    { name: "Apex Brand Cue Stand Black for 10 Cues Set of 1", url: "https://snookercart.com/buy-product/ols/products/apex-brand-cue-stand-black-for-10-cues-set-of-1-9d1808" },
    { name: "Apex Brand Cue Stand Golden for 10 Cues Set of 1", url: "https://snookercart.com/buy-product/ols/products/apex-brand-cue-stand-golden-for-10-cues-set-of-1-9a3ff9" },
    { name: "Apex Brand Cue Stand Mahagony for 10 Cues Set of 1", url: "https://snookercart.com/buy-product/ols/products/apex-brand-cue-stand-mahagony-for-10-cues-set-of-1-6ceec0" },
    { name: "Apex Brand Cue Stand Silver for 10 Cues Set of 1", url: "https://snookercart.com/buy-product/ols/products/apex-brand-cue-stand-silver-for-10-cues-set-of-1-c55113" },
    { name: "Apex Brand Cue Stand Wooden finish color for 10 Cues Set of 1", url: "https://snookercart.com/buy-product/ols/products/apex-brand-cue-stand-wooden-finish-color-for-10-cues-set-of-1-fa2019" },
    { name: "Apex Chalk Pouch Blue", url: "https://snookercart.com/buy-product/ols/products/apex-chalk-pouch-blue-b32d26" },
    { name: "Apex Chalk Pouch Brown", url: "https://snookercart.com/buy-product/ols/products/apex-chalk-pouch-brown-1d90a2" },
    { name: "Apex Chalk Pouch Cherry Red", url: "https://snookercart.com/buy-product/ols/products/apex-chalk-pouch-cherry-red-f8af92" },
    { name: "Apex Chalk Pouch Coffe Color", url: "https://snookercart.com/buy-product/ols/products/apex-chalk-pouch-coffe-color-0078a8" },
    { name: "Apex Chalk Pouch Dark Brown", url: "https://snookercart.com/buy-product/ols/products/apex-chalk-pouch-dark-brown-d27df0" },
    { name: "Apex Chalk Pouch Golden", url: "https://snookercart.com/buy-product/ols/products/apex-chalk-pouch-golden-e62407" },
    { name: "Apex Chalk Pouch Green", url: "https://snookercart.com/buy-product/ols/products/apex-chalk-pouch-green-761f1c" },
    { name: "Apex Chalk Pouch Red", url: "https://snookercart.com/buy-product/ols/products/apex-chalk-pouch-red-8abe21" },
    { name: "Apex Chalk Pouch Violet", url: "https://snookercart.com/buy-product/ols/products/apex-chalk-pouch-violet-7c0625" },
    { name: "Apex Classic Cue 1 Piece Customised", url: "https://snookercart.com/buy-product/ols/products/apex-classic-cue-1-piece-customised-c27362" },
    { name: "Apex Inner Pocket Sets Pack of 6 Light Brown", url: "https://snookercart.com/buy-product/ols/products/apex-inner-pocket-sets-pack-of-6-light-brown-e604c1" },
    { name: "Apex Leather Case Black 1 Piece", url: "https://snookercart.com/buy-product/ols/products/apex-leather-case-black-1-piece-73fb2e" },
    { name: "Apex Leather Case Black 3/4", url: "https://snookercart.com/buy-product/ols/products/apex-leather-case-black-3-4-79edf9" },
    { name: "Apex Leather Case Blue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/apex-leather-case-blue-1-piece-26e7c7" },
    { name: "Apex Leather Case Blue 3/4", url: "https://snookercart.com/buy-product/ols/products/apex-leather-case-blue-3-4-b67ddb" },
    { name: "Apex Leather Case Green 1 Piece", url: "https://snookercart.com/buy-product/ols/products/apex-leather-case-green-1-piece-6af8be" },
    { name: "Apex Leather Case Green 3/4", url: "https://snookercart.com/buy-product/ols/products/apex-leather-case-green-3-4-17a8d1" },
    { name: "Apex Leather Case Orange 1 Piece", url: "https://snookercart.com/buy-product/ols/products/apex-leather-case-orange-1-piece-effe0d" },
    { name: "Apex Leather Case Orange 3/4", url: "https://snookercart.com/buy-product/ols/products/apex-leather-case-orange-3-4-83b7c2" },
    { name: "Apex Pocket Leather Pack of 6 Light Brown", url: "https://snookercart.com/buy-product/ols/products/apex-pocket-leather-pack-of-6-light-brown-e1a932" },
    { name: "Apex Pool Table Railing Pack of 6 Black", url: "https://snookercart.com/buy-product/ols/products/apex-pool-table-railing-pack-of-6-black-804775" },
    { name: "Apex Premium Case Brown 1 Piece", url: "https://snookercart.com/buy-product/ols/products/apex-premium-case-brown-1-piece-4eb12e" },
    { name: "Apex Premium Case Navy Blue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/apex-premium-case-navy-blue-1-piece-5fa75b" },
    { name: "Apex Premium Case Red 1 Piece", url: "https://snookercart.com/buy-product/ols/products/apex-premium-case-red-1-piece-c0f085" },
    { name: "Apex Victory Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/apex-victory-cue-1-piece-65ee2f" },
    { name: "Aramith Ball Cleaner 250ml", url: "https://snookercart.com/buy-product/ols/products/aramith-ball-cleaner-250ml-6b5a07" },
    { name: "Aramith Premier Pool Ball set 57.2 In Suit Case", url: "https://snookercart.com/buy-product/ols/products/aramith-premier-pool-ball-set-57-2-in-suit-case-562060" },
    { name: "Aramith Premier Snooker Ballset 52.4mm Old Balls", url: "https://snookercart.com/buy-product/ols/products/aramith-premier-snooker-ballset-52-4mm-old-balls-be4c3f" },
    { name: "Aramith Super Pro Pool Ballset 57.2mm", url: "https://snookercart.com/buy-product/ols/products/aramith-super-pro-pool-ballset-57-2mm-046630" },
    { name: "Ball Cleaning Plates", url: "https://snookercart.com/buy-product/ols/products/ball-cleaning-plates-4f029a" },
    { name: "Ball Position Marker", url: "https://snookercart.com/buy-product/ols/products/ball-position-marker-521538" },
    { name: "Belgian Aramitch Balls Set of 3", url: "https://snookercart.com/buy-product/ols/products/belgian-aramitch-balls-set-of-3-1d72bb" },
    { name: "Billee Cue 1/2", url: "https://snookercart.com/buy-product/ols/products/billee-cue-1-2-40a1e4" },
    { name: "Billie Chalk Single Tip Dark Blue", url: "https://snookercart.com/buy-product/ols/products/billie-chalk-single-tip-dark-blue-f3cc25" },
    { name: "Bison Tip Hard 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/bison-tip-hard-10mm-blue-ff91d7" },
    { name: "Blue Diamond Chalk Single Blue", url: "https://snookercart.com/buy-product/ols/products/blue-diamond-chalk-single-blue-6a1970" },
    { name: "Blue Diamond Gloves Black", url: "https://snookercart.com/buy-product/ols/products/blue-diamond-gloves-black-f1c7fc" },
    { name: "Blue Diamond Tip 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/blue-diamond-tip-10mm-blue-e10825" },
    { name: "Blue Diamond Tip 11mm Blue", url: "https://snookercart.com/buy-product/ols/products/blue-diamond-tip-11mm-blue-a687cd" },
    { name: "Boutique Billiard Gloves Blue", url: "https://snookercart.com/buy-product/ols/products/boutique-billiard-gloves-blue-1e8ac7" },
    { name: "Boutique Billiard Gloves Red", url: "https://snookercart.com/buy-product/ols/products/boutique-billiard-gloves-red-cee5e1" },
    { name: "Bridge Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/bridge-cue-3-4-283e60" },
    { name: "Bridge Jack Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/bridge-jack-cue-3-4-aa8716" },
    { name: "Bridge Rebel Black", url: "https://snookercart.com/buy-product/ols/products/bridge-rebel-black-ae8f22" },
    { name: "Bridge Rebel Cue 1/2", url: "https://snookercart.com/buy-product/ols/products/bridge-rebel-cue-1-2-176900" },
    { name: "Brunswik Blue Daimond Tip 9mm Blue", url: "https://snookercart.com/buy-product/ols/products/brunswik-blue-daimond-tip-9mm-blue-b08477" },
    { name: "Brunswik Chalk Single Tip Dark Blue", url: "https://snookercart.com/buy-product/ols/products/brunswik-chalk-single-tip-dark-blue-741013" },
    { name: "Brunswik Tip 9mm Blue", url: "https://snookercart.com/buy-product/ols/products/brunswik-tip-9mm-blue-135b9b" },
    { name: "Buffalo Tip 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/buffalo-tip-10mm-blue-3d4203" },
    { name: "Burroughes and Watts Tip 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/burroughes-and-watts-tip-10mm-blue-a90c2a" },
    { name: "Butt Protector", url: "https://snookercart.com/buy-product/ols/products/butt-protector-828449" },
    { name: "Case Cover Black 3/4", url: "https://snookercart.com/buy-product/ols/products/case-cover-black-3-4-54b17b" },
    { name: "Case Cover Blue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/case-cover-blue-1-piece-73b694" },
    { name: "Century Chalk Single Blue", url: "https://snookercart.com/buy-product/ols/products/century-chalk-single-blue-a28535" },
    { name: "Century Chalk Single Light Green", url: "https://snookercart.com/buy-product/ols/products/century-chalk-single-light-green-1aa9ff" },
    { name: "Century Cue Cover 1 Piece", url: "https://snookercart.com/buy-product/ols/products/century-cue-cover-1-piece-fc67ee" },
    { name: "Century ferrule 10", url: "https://snookercart.com/buy-product/ols/products/century-ferrule-10-f58875" },
    { name: "Century ferrule 9.1", url: "https://snookercart.com/buy-product/ols/products/century-ferrule-9-1-d65fa3" },
    { name: "Century ferrule 9.2", url: "https://snookercart.com/buy-product/ols/products/century-ferrule-9-2-60494e" },
    { name: "Century ferrule 9.3", url: "https://snookercart.com/buy-product/ols/products/century-ferrule-9-3-a7198c" },
    { name: "Century ferrule 9.5", url: "https://snookercart.com/buy-product/ols/products/century-ferrule-9-5-e7ef5d" },
    { name: "Century ferrule 9.6", url: "https://snookercart.com/buy-product/ols/products/century-ferrule-9-6-56b4c0" },
    { name: "Century Pro-X Tip 11mm Blue ( Pack of 1 )", url: "https://snookercart.com/buy-product/ols/products/century-pro-x-tip-11mm-blue-pack-of-1-14c19b" },
    { name: "Century Tip G1 Soft 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/century-tip-g1-soft-10mm-blue-4ef024" },
    { name: "Century Tip G2 Med 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/century-tip-g2-med-10mm-blue-b7208f" },
    { name: "Century Tip G3 Med-Hard10mm Blue", url: "https://snookercart.com/buy-product/ols/products/century-tip-g3-med-hard10mm-blue-b2f22c" },
    { name: "Century Tip G4 Hard 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/century-tip-g4-hard-10mm-blue-2e6f1e" },
    { name: "Century Tip G5 Tip Super Hard 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/century-tip-g5-tip-super-hard-10mm-blue-bd7a3d" },
    { name: "Century Towel Small Size", url: "https://snookercart.com/buy-product/ols/products/century-towel-small-size-36c55c" },
    { name: "Ceramic Triangle", url: "https://snookercart.com/buy-product/ols/products/ceramic-triangle-b76975" },
    { name: "Chinese Dragaon Cues 1 Piece", url: "https://snookercart.com/buy-product/ols/products/chinese-dragaon-cues-1-piece-7685d3" },
    { name: "Chinese Pool Ballset Black 52.4mm", url: "https://snookercart.com/buy-product/ols/products/chinese-pool-ballset-black-52-4mm-f16f61" },
    { name: "Chinese Pool Ballset Green 52.4mm", url: "https://snookercart.com/buy-product/ols/products/chinese-pool-ballset-green-52-4mm-ef4e1b" },
    { name: "Chuang Pool Tip 13.5mm Light Grey", url: "https://snookercart.com/buy-product/ols/products/chuang-pool-tip-13-5mm-light-grey-6e5c95" },
    { name: "Clover Tip 12mm Grey", url: "https://snookercart.com/buy-product/ols/products/clover-tip-12mm-grey-eb8d0c" },
    { name: "Cotton Pocket Net Pack of 6 White", url: "https://snookercart.com/buy-product/ols/products/cotton-pocket-net-pack-of-6-white-a01af7" },
    { name: "Cue Cover Black 1/2", url: "https://snookercart.com/buy-product/ols/products/cue-cover-black-1-2-a14acb" },
    { name: "Cue Cover Black 3/4", url: "https://snookercart.com/buy-product/ols/products/cue-cover-black-3-4-60520a" },
    { name: "Cue Cover Black 3/4 ( Black & White strips )", url: "https://snookercart.com/buy-product/ols/products/cue-cover-black-3-4-black-white-strips-d8a60c" },
    { name: "Cue Cover with Spunch Black 3/4", url: "https://snookercart.com/buy-product/ols/products/cue-cover-with-spunch-black-3-4-daff7c" },
    { name: "Cue Cover with Spunch Black-Yellow 3/4", url: "https://snookercart.com/buy-product/ols/products/cue-cover-with-spunch-black-yellow-3-4-3ab582" },
    { name: "Cue shaft polisher double sided", url: "https://snookercart.com/buy-product/ols/products/cue-shaft-polisher-double-sided-45db13" },
    { name: "Cue Tip Shaper", url: "https://snookercart.com/buy-product/ols/products/cue-tip-shaper-62b5ff" },
    { name: "Cue Tip Shaper Dragon Tongue", url: "https://snookercart.com/buy-product/ols/products/cue-tip-shaper-dragon-tongue-d85600" },
    { name: "Cue Tip Shaper Premium", url: "https://snookercart.com/buy-product/ols/products/cue-tip-shaper-premium-f8da18" },
    { name: "Cue towel shaft", url: "https://snookercart.com/buy-product/ols/products/cue-towel-shaft-641ce3" },
    { name: "Cue Wall Stand Brown", url: "https://snookercart.com/buy-product/ols/products/cue-wall-stand-brown-db7c1f" },
    { name: "Deer Tip 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/deer-tip-10mm-blue-d3f76d" },
    { name: "Delux Billiards Towel", url: "https://snookercart.com/buy-product/ols/products/delux-billiards-towel-896f53" },
    { name: "Dotted Cue Ball", url: "https://snookercart.com/buy-product/ols/products/dotted-cue-ball-3721fe" },
    { name: "Double Black Leather Tip 10mm Pack of 3 Black", url: "https://snookercart.com/buy-product/ols/products/double-black-leather-tip-10mm-pack-of-3-black-dd9735" },
    { name: "Dufferin Canada Cue 1/2", url: "https://snookercart.com/buy-product/ols/products/dufferin-canada-cue-1-2-491857" },
    { name: "Dust Cover for Mini Snooker Black (5X10 feet)", url: "https://snookercart.com/buy-product/ols/products/dust-cover-for-mini-snooker-black-5x10-feet-1260ab" },
    { name: "Dust Cover for Pool Black ( 4X8 feet)", url: "https://snookercart.com/buy-product/ols/products/dust-cover-for-pool-black-4x8-feet-0593cc" },
    { name: "Dust Cover for Snooker Black ( 6X12 feet)", url: "https://snookercart.com/buy-product/ols/products/dust-cover-for-snooker-black-6x12-feet-a66739" },
    { name: "Dust Cover for Snooker Cloth Green ( 6X12 feet)", url: "https://snookercart.com/buy-product/ols/products/dust-cover-for-snooker-cloth-green-6x12-feet-daf9ce" },
    { name: "Dust Cover Xingpai Leather Brown (4.5X9 feet)", url: "https://snookercart.com/buy-product/ols/products/dust-cover-xingpai-leather-brown-4-5x9-feet-f6c0a7" },
    { name: "Dyna Spehere Palladium 57.2mm", url: "https://snookercart.com/buy-product/ols/products/dyna-spehere-palladium-57-2mm-ec6eff" },
    { name: "Dyna Spehere Snooker Ballset 52.4mm ( 172 Model )", url: "https://snookercart.com/buy-product/ols/products/dyna-spehere-snooker-ballset-52-4mm-172-model-5d49df" },
    { name: "Dyna Spehere Snooker Ballset Silver 52.4mm", url: "https://snookercart.com/buy-product/ols/products/dyna-spehere-snooker-ballset-silver-52-4mm-581093" },
    { name: "Ebony Hunter Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/ebony-hunter-cue-3-4-68b677" },
    { name: "Electronics Score Board with remote", url: "https://snookercart.com/buy-product/ols/products/electronics-score-board-with-remote-b64057" },
    { name: "Elk Master Pro Tip 10mm Light Grey", url: "https://snookercart.com/buy-product/ols/products/elk-master-pro-tip-10mm-light-grey-aac7bc" },
    { name: "Elk Master Tip Club 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/elk-master-tip-club-10mm-blue-663581" },
    { name: "Elk Master Tip Club 9mm Blue", url: "https://snookercart.com/buy-product/ols/products/elk-master-tip-club-9mm-blue-910ea4" },
    { name: "Elk Master Tip OG 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/elk-master-tip-og-10mm-blue-59f89e" },
    { name: "Elk Master Tip OG 9mm Blue", url: "https://snookercart.com/buy-product/ols/products/elk-master-tip-og-9mm-blue-8cd9ed" },
    { name: "Europian Pool Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/europian-pool-cue-1-piece-9a4e1b" },
    { name: "Extended Spider Head", url: "https://snookercart.com/buy-product/ols/products/extended-spider-head-d24e18" },
    { name: "Fibre Glass rest Stick", url: "https://snookercart.com/buy-product/ols/products/fibre-glass-rest-stick-5f985f" },
    { name: "Gloves Black", url: "https://snookercart.com/buy-product/ols/products/gloves-black-532e55" },
    { name: "Gloves Black Sack", url: "https://snookercart.com/buy-product/ols/products/gloves-black-sack-1dc3a2" },
    { name: "Gloves Blue", url: "https://snookercart.com/buy-product/ols/products/gloves-blue-bcc0ff" },
    { name: "Gloves Brown", url: "https://snookercart.com/buy-product/ols/products/gloves-brown-957d15" },
    { name: "Grand Tip 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/grand-tip-10mm-blue-f7000e" },
    { name: "GT Magnetic round Chalk Holder Red-Black", url: "https://snookercart.com/buy-product/ols/products/gt-magnetic-round-chalk-holder-red-black-0bfd4d" },
    { name: "Hand made Professional Club Cue 1/2", url: "https://snookercart.com/buy-product/ols/products/hand-made-professional-club-cue-1-2-c6df8e" },
    { name: "Hand made Professional Club Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/hand-made-professional-club-cue-3-4-f8e351" },
    { name: "Hi-Chrome Tip Single 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/hi-chrome-tip-single-10mm-blue-ca0549" },
    { name: "Hong Chai Chalk Single Blue", url: "https://snookercart.com/buy-product/ols/products/hong-chai-chalk-single-blue-b9609d" },
    { name: "Inner Pockets Set of 6 Brown", url: "https://snookercart.com/buy-product/ols/products/inner-pockets-set-of-6-brown-c15058" },
    { name: "Inner Pockets Set of 6 Light Brown - Apex", url: "https://snookercart.com/buy-product/ols/products/inner-pockets-set-of-6-light-brown-apex-1e3626" },
    { name: "Jack Cue 1/2", url: "https://snookercart.com/buy-product/ols/products/jack-cue-1-2-7abbf2" },
    { name: "Jack Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/jack-cue-3-4-8908ca" },
    { name: "Janeson Cue Club 1/2", url: "https://snookercart.com/buy-product/ols/products/janeson-cue-club-1-2-5429fe" },
    { name: "JDH Ball set", url: "https://snookercart.com/buy-product/ols/products/jdh-ball-set-62fa10" },
    { name: "JDH Club cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/jdh-club-cue-1-piece-b525ef" },
    { name: "JDH Pool Ballset 52.4mm", url: "https://snookercart.com/buy-product/ols/products/jdh-pool-ballset-52-4mm-139c82" },
    { name: "Jupiter Chalk Single Dark Green", url: "https://snookercart.com/buy-product/ols/products/jupiter-chalk-single-dark-green-106a3f" },
    { name: "Kamui Black Tip Med 10mm", url: "https://snookercart.com/buy-product/ols/products/kamui-black-tip-med-10mm-1c7a1f" },
    { name: "Kamui Brand Logo Leather", url: "https://snookercart.com/buy-product/ols/products/kamui-brand-logo-leather-a703d6" },
    { name: "Kamui Brown Tip Med 10mm", url: "https://snookercart.com/buy-product/ols/products/kamui-brown-tip-med-10mm-08da07" },
    { name: "Kamui Case Cover For 2 Cues Black 1/2", url: "https://snookercart.com/buy-product/ols/products/kamui-case-cover-for-2-cues-black-1-2-7fda95" },
    { name: "Kamui Clear Bridge Head Transparent", url: "https://snookercart.com/buy-product/ols/products/kamui-clear-bridge-head-transparent-eb7451" },
    { name: "Kamui Roku Chalk Single Light Blue", url: "https://snookercart.com/buy-product/ols/products/kamui-roku-chalk-single-light-blue-eef211" },
    { name: "Kamui Sai Tip 14mm Black", url: "https://snookercart.com/buy-product/ols/products/kamui-sai-tip-14mm-black-81b118" },
    { name: "Kamui Tip 11mm", url: "https://snookercart.com/buy-product/ols/products/kamui-tip-11mm-230b22" },
    { name: "Kamui Tip Protector Black Single", url: "https://snookercart.com/buy-product/ols/products/kamui-tip-protector-black-single-c07353" },
    { name: "Kamui Tip Protector Red Single", url: "https://snookercart.com/buy-product/ols/products/kamui-tip-protector-red-single-e934f4" },
    { name: "Kamui Tip Single 10mm Brown", url: "https://snookercart.com/buy-product/ols/products/kamui-tip-single-10mm-brown-dc23fe" },
    { name: "Key Chain Crystal Pack of 16", url: "https://snookercart.com/buy-product/ols/products/key-chain-crystal-pack-of-16-6f6819" },
    { name: "Key Chain Radium Crystal + other Pack of 16", url: "https://snookercart.com/buy-product/ols/products/key-chain-radium-crystal-other-pack-of-16-42a682" },
    { name: "Key Chain Small Pack of 16", url: "https://snookercart.com/buy-product/ols/products/key-chain-small-pack-of-16-f4575f" },
    { name: "Key Chains Pack of 16", url: "https://snookercart.com/buy-product/ols/products/key-chains-pack-of-16-217934" },
    { name: "Kuki - NAP settler", url: "https://snookercart.com/buy-product/ols/products/kuki-nap-settler-b99b60" },
    { name: "Lead Super American Pool Cue 1/2", url: "https://snookercart.com/buy-product/ols/products/lead-super-american-pool-cue-1-2-a06d02" },
    { name: "Leather Case Black-Brown 3/4", url: "https://snookercart.com/buy-product/ols/products/leather-case-black-brown-3-4-cc051b" },
    { name: "Leather Case Black-Grey 3/4", url: "https://snookercart.com/buy-product/ols/products/leather-case-black-grey-3-4-3d5419" },
    { name: "Leather Case Black-Red 3/4", url: "https://snookercart.com/buy-product/ols/products/leather-case-black-red-3-4-4cf8a7" },
    { name: "Leather Case Black-White 3/4", url: "https://snookercart.com/buy-product/ols/products/leather-case-black-white-3-4-a5d27a" },
    { name: "Leather Case Black-Yellow 3/4", url: "https://snookercart.com/buy-product/ols/products/leather-case-black-yellow-3-4-d457ae" },
    { name: "Leather Case Leopard 3/4", url: "https://snookercart.com/buy-product/ols/products/leather-case-leopard-3-4-ed8f03" },
    { name: "Leather Case Leopard One Piece", url: "https://snookercart.com/buy-product/ols/products/leather-case-leopard-one-piece-ef12e7" },
    { name: "Leather case with Num Lock Black 1 piece", url: "https://snookercart.com/buy-product/ols/products/leather-case-with-num-lock-black-1-piece-01b3c1" },
    { name: "Leather case with Num Lock Brown 1 piece", url: "https://snookercart.com/buy-product/ols/products/leather-case-with-num-lock-brown-1-piece-edc8a9" },
    { name: "Leather for Inner Pocket Pack of 6 Hard Light Brown (Apex)", url: "https://snookercart.com/buy-product/ols/products/leather-for-inner-pocket-pack-of-6-hard-light-brown-apex-153ab9" },
    { name: "Leather for Upper Pocket Pack of 6 Hard Black", url: "https://snookercart.com/buy-product/ols/products/leather-for-upper-pocket-pack-of-6-hard-black-53529c" },
    { name: "Leather for Upper Pocket Pack of 6 Hard Brown", url: "https://snookercart.com/buy-product/ols/products/leather-for-upper-pocket-pack-of-6-hard-brown-be484d" },
    { name: "Leather for Upper Pocket Pack of 6 Hard Light Brown", url: "https://snookercart.com/buy-product/ols/products/leather-for-upper-pocket-pack-of-6-hard-light-brown-9804f4" },
    { name: "Leather for Upper Pocket Pack of 6 Soft Brown", url: "https://snookercart.com/buy-product/ols/products/leather-for-upper-pocket-pack-of-6-soft-brown-7114f9" },
    { name: "Leather for Upper Pocket Pack of 6 Soft Grey", url: "https://snookercart.com/buy-product/ols/products/leather-for-upper-pocket-pack-of-6-soft-grey-8a1c8b" },
    { name: "Leather for Upper Pocket Pack of 6 Soft Light Brown", url: "https://snookercart.com/buy-product/ols/products/leather-for-upper-pocket-pack-of-6-soft-light-brown-06d30d" },
    { name: "Leather for Upper Pocket Pack of 6 Soft Red", url: "https://snookercart.com/buy-product/ols/products/leather-for-upper-pocket-pack-of-6-soft-red-70b6b9" },
    { name: "Leather Tip Protector", url: "https://snookercart.com/buy-product/ols/products/leather-tip-protector-2847f7" },
    { name: "LED Light 36 Watt", url: "https://snookercart.com/buy-product/ols/products/led-light-36-watt-fdab95" },
    { name: "Legend Chalk Single Blue", url: "https://snookercart.com/buy-product/ols/products/legend-chalk-single-blue-abee1c" },
    { name: "Legend Tip Blue", url: "https://snookercart.com/buy-product/ols/products/legend-tip-blue-8345fe" },
    { name: "Long rest Head", url: "https://snookercart.com/buy-product/ols/products/long-rest-head-ef249f" },
    { name: "Long rest Head Xingpai", url: "https://snookercart.com/buy-product/ols/products/long-rest-head-xingpai-3dbceb" },
    { name: "LP Black Tips A 10mm Light Green", url: "https://snookercart.com/buy-product/ols/products/lp-black-tips-a-10mm-light-green-5e1564" },
    { name: "LP Blue Tips B 10mm Light Green", url: "https://snookercart.com/buy-product/ols/products/lp-blue-tips-b-10mm-light-green-609c5b" },
    { name: "LP Club Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/lp-club-cue-1-piece-10db2d" },
    { name: "LP Club Tips A Pack of 50 10.5mm", url: "https://snookercart.com/buy-product/ols/products/lp-club-tips-a-pack-of-50-10-5mm-d5c960" },
    { name: "LP Club Tips A Pack of 50 11mm Blue", url: "https://snookercart.com/buy-product/ols/products/lp-club-tips-a-pack-of-50-11mm-blue-793963" },
    { name: "LP Club Tips B Pack of 50 10.5mm Blue", url: "https://snookercart.com/buy-product/ols/products/lp-club-tips-b-pack-of-50-10-5mm-blue-96cff1" },
    { name: "LP Dream Tip 10mm Light Green", url: "https://snookercart.com/buy-product/ols/products/lp-dream-tip-10mm-light-green-8d4154" },
    { name: "Lp Extension Small (6-Inch) Black", url: "https://snookercart.com/buy-product/ols/products/lp-extension-small-6-inch-black-bb306b" },
    { name: "LP Gen3 Tip soft 10.5mm Light Green", url: "https://snookercart.com/buy-product/ols/products/lp-gen3-tip-soft-10-5mm-light-green-955332" },
    { name: "LP Premium Cue Brown 3/4", url: "https://snookercart.com/buy-product/ols/products/lp-premium-cue-brown-3-4-df70c4" },
    { name: "LP Premium Cue Maroon 3/4", url: "https://snookercart.com/buy-product/ols/products/lp-premium-cue-maroon-3-4-d551ee" },
    { name: "LP Professional Pack of 6 Tip 11mm", url: "https://snookercart.com/buy-product/ols/products/lp-professional-pack-of-6-tip-11mm-0c6f1f" },
    { name: "LP Super Dream Tip (Pack of 1) Light green", url: "https://snookercart.com/buy-product/ols/products/lp-super-dream-tip-pack-of-1-light-green-ddfb74" },
    { name: "LP Super Pro Tip (Pack of 1) 10mm Black", url: "https://snookercart.com/buy-product/ols/products/lp-super-pro-tip-pack-of-1-10mm-black-71959f" },
    { name: "Lp Super SS Dream M1 Tip 11mm Blue", url: "https://snookercart.com/buy-product/ols/products/lp-super-ss-dream-m1-tip-11mm-blue-624502" },
    { name: "LP Tip A Grade 13mm light Green", url: "https://snookercart.com/buy-product/ols/products/lp-tip-a-grade-13mm-light-green-448dd3" },
    { name: "LP White Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/lp-white-cue-3-4-84fbff" },
    { name: "Magnetic Chalk Holder Black", url: "https://snookercart.com/buy-product/ols/products/magnetic-chalk-holder-black-a7dc58" },
    { name: "Maixmus ( Cue craft design ) Aluminium 1 Piece Golden Cue Case - Special Category", url: "https://snookercart.com/buy-product/ols/products/maixmus-cue-craft-design-aluminium-1-piece-golden-cue-case-special-category-af371b" },
    { name: "Mandum Ball set", url: "https://snookercart.com/buy-product/ols/products/mandum-ball-set-375eae" },
    { name: "Mandum Tip 13mm Grey", url: "https://snookercart.com/buy-product/ols/products/mandum-tip-13mm-grey-838244" },
    { name: "Mandun Cue Shaft Single Black-White", url: "https://snookercart.com/buy-product/ols/products/mandun-cue-shaft-single-black-white-0fdb28" },
    { name: "Mandun Gloves Black", url: "https://snookercart.com/buy-product/ols/products/mandun-gloves-black-126502" },
    { name: "Mandun Wax 50gm", url: "https://snookercart.com/buy-product/ols/products/mandun-wax-50gm-cb71df" },
    { name: "Mark Shelby Tip 10mm Black", url: "https://snookercart.com/buy-product/ols/products/mark-shelby-tip-10mm-black-ad9dd2" },
    { name: "Master Chalk Single Black", url: "https://snookercart.com/buy-product/ols/products/master-chalk-single-black-b989c3" },
    { name: "Master Chalk Single Blue", url: "https://snookercart.com/buy-product/ols/products/master-chalk-single-blue-ebc713" },
    { name: "Master Chalk Single Brown", url: "https://snookercart.com/buy-product/ols/products/master-chalk-single-brown-1b10cf" },
    { name: "Master Chalk Single Maroon", url: "https://snookercart.com/buy-product/ols/products/master-chalk-single-maroon-0e6ba6" },
    { name: "Master Chalk Single Red", url: "https://snookercart.com/buy-product/ols/products/master-chalk-single-red-27d1a7" },
    { name: "Master Club Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/master-club-cue-3-4-67cca5" },
    { name: "Master Magnetic Chalk Holder Black", url: "https://snookercart.com/buy-product/ols/products/master-magnetic-chalk-holder-black-a04493" },
    { name: "Master Magnetic Chalk Holder White", url: "https://snookercart.com/buy-product/ols/products/master-magnetic-chalk-holder-white-928b64" },
    { name: "Master Mini Butt 6" Plastic", url: "https://snookercart.com/buy-product/ols/products/master-mini-butt-6-plastic-1dbb7f" },
    { name: "Master Pro Butt Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/master-pro-butt-cue-3-4-c3f094" },
    { name: "Master Tip 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/master-tip-10mm-blue-c8089b" },
    { name: "Maximus Premium Cue 1 Piece - Special Category", url: "https://snookercart.com/buy-product/ols/products/maximus-premium-cue-1-piece-special-category-47cf29" },
    { name: "Maximus Premium Cue 3/4 - Special Category", url: "https://snookercart.com/buy-product/ols/products/maximus-premium-cue-3-4-special-category-63fdb3" },
    { name: "Maximus Premium Cue 3/4 Maple - Special Category", url: "https://snookercart.com/buy-product/ols/products/maximus-premium-cue-3-4-maple-special-category-2407e7" },
    { name: "Melin Magnetic Dual Chalk Holder Black-Red", url: "https://snookercart.com/buy-product/ols/products/melin-magnetic-dual-chalk-holder-black-red-d28529" },
    { name: "Melin Table Cue Stand for 2 Cues", url: "https://snookercart.com/buy-product/ols/products/melin-table-cue-stand-for-2-cues-72da13" },
    { name: "Melin Table Cue Stand for 3 Cues", url: "https://snookercart.com/buy-product/ols/products/melin-table-cue-stand-for-3-cues-07bff8" },
    { name: "Melin Table Cue Stand for 5 Cues", url: "https://snookercart.com/buy-product/ols/products/melin-table-cue-stand-for-5-cues-eeb441" },
    { name: "Mike Wooleridge Tip 9mm Blue", url: "https://snookercart.com/buy-product/ols/products/mike-wooleridge-tip-9mm-blue-e6b3e8" },
    { name: "Mix Club Tip Blue", url: "https://snookercart.com/buy-product/ols/products/mix-club-tip-blue-4f07bd" },
    { name: "MW Ball Cleaner 150ml", url: "https://snookercart.com/buy-product/ols/products/mw-ball-cleaner-150ml-4f0938" },
    { name: "NRC Pack of 6", url: "https://snookercart.com/buy-product/ols/products/nrc-pack-of-6-606c80" },
    { name: "Omin ( Cue craft design ) Aluminium 1 Piece Golden Cue Case - Special Category", url: "https://snookercart.com/buy-product/ols/products/omin-cue-craft-design-aluminium-1-piece-golden-cue-case-special-category-7dc455" },
    { name: "Omin 3/4 Premium Cue Cover Leather - Special Category", url: "https://snookercart.com/buy-product/ols/products/omin-3-4-premium-cue-cover-leather-special-category-d4036c" },
    { name: "Omin American Pool Cue 1/2", url: "https://snookercart.com/buy-product/ols/products/omin-american-pool-cue-1-2-398a78" },
    { name: "Omin Basic Cue 3/4 - Special Category", url: "https://snookercart.com/buy-product/ols/products/omin-basic-cue-3-4-special-category-1bcbb5" },
    { name: "Omin Butt protector Brass", url: "https://snookercart.com/buy-product/ols/products/omin-butt-protector-brass-1495c2" },
    { name: "Omin Chalk Holder Black", url: "https://snookercart.com/buy-product/ols/products/omin-chalk-holder-black-3aa2af" },
    { name: "Omin Chalk Holder Black Without Cap", url: "https://snookercart.com/buy-product/ols/products/omin-chalk-holder-black-without-cap-8b37b1" },
    { name: "Omin Chalk Holder Brown", url: "https://snookercart.com/buy-product/ols/products/omin-chalk-holder-brown-7aeda0" },
    { name: "Omin Chalk Holder Light Brown Without Cap", url: "https://snookercart.com/buy-product/ols/products/omin-chalk-holder-light-brown-without-cap-3afaf3" },
    { name: "Omin Chalk Holder with Cap Black", url: "https://snookercart.com/buy-product/ols/products/omin-chalk-holder-with-cap-black-41a1ba" },
    { name: "Omin Chalk Pouch Black", url: "https://snookercart.com/buy-product/ols/products/omin-chalk-pouch-black-034fe9" },
    { name: "Omin Chalk Single Dark Blue", url: "https://snookercart.com/buy-product/ols/products/omin-chalk-single-dark-blue-dc1404" },
    { name: "Omin Chalk Single Dark Green", url: "https://snookercart.com/buy-product/ols/products/omin-chalk-single-dark-green-dbe3f8" },
    { name: "Omin Champion 3/4", url: "https://snookercart.com/buy-product/ols/products/omin-champion-3-4-5653b8" },
    { name: "Omin Champion Cue 3/4 - Special Category", url: "https://snookercart.com/buy-product/ols/products/omin-champion-cue-3-4-special-category-80bcc6" },
    { name: "Omin Classic Cue 1 Piece- Special Category", url: "https://snookercart.com/buy-product/ols/products/omin-classic-cue-1-piece-special-category-976626" },
    { name: "Omin Cue Cleaner Spary", url: "https://snookercart.com/buy-product/ols/products/omin-cue-cleaner-spary-13029b" },
    { name: "Omin Cue Oil 10ml", url: "https://snookercart.com/buy-product/ols/products/omin-cue-oil-10ml-0ac6d6" },
    { name: "Omin Extension (6-Inch) Black", url: "https://snookercart.com/buy-product/ols/products/omin-extension-6-inch-black-9fd2a9" },
    { name: "Omin Extension (6-Inch) Black - Plastic", url: "https://snookercart.com/buy-product/ols/products/omin-extension-6-inch-black-plastic-50d69f" },
    { name: "Omin Extension (6-Inch) Golden", url: "https://snookercart.com/buy-product/ols/products/omin-extension-6-inch-golden-bc2da3" },
    { name: "Omin Extension (6-Inch) SkyBlue", url: "https://snookercart.com/buy-product/ols/products/omin-extension-6-inch-skyblue-730383" },
    { name: "Omin Extension (9-Inch) Black", url: "https://snookercart.com/buy-product/ols/products/omin-extension-9-inch-black-7af1e1" },
    { name: "Omin Extension (9-Inch) Black-Green", url: "https://snookercart.com/buy-product/ols/products/omin-extension-9-inch-black-green-e558e4" },
    { name: "Omin Extension (9-Inch) Golden", url: "https://snookercart.com/buy-product/ols/products/omin-extension-9-inch-golden-41a6b9" },
    { name: "Omin Extension (9-Inch) Silver", url: "https://snookercart.com/buy-product/ols/products/omin-extension-9-inch-silver-7fe9d7" },
    { name: "Omin Extension Black - Silver 18 Inch", url: "https://snookercart.com/buy-product/ols/products/omin-extension-black-silver-18-inch-f7d2bf" },
    { name: "Omin Extension Black 18 Inch", url: "https://snookercart.com/buy-product/ols/products/omin-extension-black-18-inch-763182" },
    { name: "Omin Extension Black-Black", url: "https://snookercart.com/buy-product/ols/products/omin-extension-black-black-8face7" },
    { name: "Omin Extension Black-Blue 12 Inch", url: "https://snookercart.com/buy-product/ols/products/omin-extension-black-blue-12-inch-7d448a" },
    { name: "Omin Extension Black-Golden", url: "https://snookercart.com/buy-product/ols/products/omin-extension-black-golden-9b03d4" },
    { name: "Omin Extension Black-Golden 18 Inch", url: "https://snookercart.com/buy-product/ols/products/omin-extension-black-golden-18-inch-36ee2a" },
    { name: "Omin Extension Golden 12 Inch", url: "https://snookercart.com/buy-product/ols/products/omin-extension-golden-12-inch-7f451e" },
    { name: "Omin Extension Silver 12 Inch", url: "https://snookercart.com/buy-product/ols/products/omin-extension-silver-12-inch-95fc36" },
    { name: "Omin Magnetic Dual Chalk Holder Blue", url: "https://snookercart.com/buy-product/ols/products/omin-magnetic-dual-chalk-holder-blue-82cbb9" },
    { name: "Omin Magnetic Dual Chalk Holder Green", url: "https://snookercart.com/buy-product/ols/products/omin-magnetic-dual-chalk-holder-green-ccdc04" },
    { name: "Omin Master Cue 3/4 - Special Category", url: "https://snookercart.com/buy-product/ols/products/omin-master-cue-3-4-special-category-5614f6" },
    { name: "Omin Original Extension (6-Inch) Black", url: "https://snookercart.com/buy-product/ols/products/omin-original-extension-6-inch-black-9c4f74" },
    { name: "Omin Perfect Cue 1 Piece - Special Category", url: "https://snookercart.com/buy-product/ols/products/omin-perfect-cue-1-piece-special-category-25fa4f" },
    { name: "Omin Premium Case Black 3/4", url: "https://snookercart.com/buy-product/ols/products/omin-premium-case-black-3-4-330849" },
    { name: "Omin Premium Case Black-Grey 1 Piece", url: "https://snookercart.com/buy-product/ols/products/omin-premium-case-black-grey-1-piece-3230ec" },
    { name: "Omin Premium Case Black-Grey 3/4", url: "https://snookercart.com/buy-product/ols/products/omin-premium-case-black-grey-3-4-10a322" },
    { name: "Omin Premium Case Red-Black", url: "https://snookercart.com/buy-product/ols/products/omin-premium-case-red-black-80dd66" },
    { name: "Omin Professional Cue 1 Piece- Special Category", url: "https://snookercart.com/buy-product/ols/products/omin-professional-cue-1-piece-special-category-e03bcf" },
    { name: "Omin Professional Cue 3/4 - Special Category", url: "https://snookercart.com/buy-product/ols/products/omin-professional-cue-3-4-special-category-68af9e" },
    { name: "Omin Red Tip 10mm", url: "https://snookercart.com/buy-product/ols/products/omin-red-tip-10mm-32048c" },
    { name: "Omin Tip 10mm", url: "https://snookercart.com/buy-product/ols/products/omin-tip-10mm-61c516" },
    { name: "Omin Tip 10mm Dark green", url: "https://snookercart.com/buy-product/ols/products/omin-tip-10mm-dark-green-6b9c91" },
    { name: "Omin Tip 9mm Brown", url: "https://snookercart.com/buy-product/ols/products/omin-tip-9mm-brown-bbe842" },
    { name: "Omin Tip Pack of 1 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/omin-tip-pack-of-1-10mm-blue-e92136" },
    { name: "Omin Tip Pack of 2 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/omin-tip-pack-of-2-10mm-blue-aa8ab6" },
    { name: "Omin Ultimate Tip 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/omin-ultimate-tip-10mm-blue-62c292" },
    { name: "Omin Wooden Mini Butt - Special Category", url: "https://snookercart.com/buy-product/ols/products/omin-wooden-mini-butt-special-category-e843ef" },
    { name: "Partners Billiard Gloves Blue", url: "https://snookercart.com/buy-product/ols/products/partners-billiard-gloves-blue-d65962" },
    { name: "Partners Billiard Gloves Grey", url: "https://snookercart.com/buy-product/ols/products/partners-billiard-gloves-grey-c0ab16" },
    { name: "Partners Billiard Gloves Red", url: "https://snookercart.com/buy-product/ols/products/partners-billiard-gloves-red-0a9a09" },
    { name: "Pheonix Tip 10mm Green", url: "https://snookercart.com/buy-product/ols/products/pheonix-tip-10mm-green-faf53c" },
    { name: "Pheonix Tip Med 11mm Blue", url: "https://snookercart.com/buy-product/ols/products/pheonix-tip-med-11mm-blue-a2a846" },
    { name: "Pheonix Tip Pack of 5 Soft 10mm Green", url: "https://snookercart.com/buy-product/ols/products/pheonix-tip-pack-of-5-soft-10mm-green-e6431d" },
    { name: "Pheonix Tip Single 11mm Green", url: "https://snookercart.com/buy-product/ols/products/pheonix-tip-single-11mm-green-9af72c" },
    { name: "Phoenix Cue Oil 30ml", url: "https://snookercart.com/buy-product/ols/products/phoenix-cue-oil-30ml-a340a0" },
    { name: "Phoenix Red Tip Med 11mm", url: "https://snookercart.com/buy-product/ols/products/phoenix-red-tip-med-11mm-588fe3" },
    { name: "Pipe Case Black 3/4", url: "https://snookercart.com/buy-product/ols/products/pipe-case-black-3-4-10bfdf" },
    { name: "Pipe Case Brown 3/4", url: "https://snookercart.com/buy-product/ols/products/pipe-case-brown-3-4-329270" },
    { name: "Pipe Case Grey 3/4", url: "https://snookercart.com/buy-product/ols/products/pipe-case-grey-3-4-823e22" },
    { name: "Plain Leather Case Black 3/4", url: "https://snookercart.com/buy-product/ols/products/plain-leather-case-black-3-4-07f9d7" },
    { name: "Plain Leather for Inner Pocket Pack of 6", url: "https://snookercart.com/buy-product/ols/products/plain-leather-for-inner-pocket-pack-of-6-89fb39" },
    { name: "Plastic Pocket Railing Pack of 6 Black Small", url: "https://snookercart.com/buy-product/ols/products/plastic-pocket-railing-pack-of-6-black-small-f01e94" },
    { name: "Plastic Pocket Railing Pack of 6 Brown Small", url: "https://snookercart.com/buy-product/ols/products/plastic-pocket-railing-pack-of-6-brown-small-eecf94" },
    { name: "Plastic Telescopic Extension Large Black-Blue", url: "https://snookercart.com/buy-product/ols/products/plastic-telescopic-extension-large-black-blue-30d89b" },
    { name: "Plastic Tip Cap", url: "https://snookercart.com/buy-product/ols/products/plastic-tip-cap-d503e4" },
    { name: "PNS 720 / Club Snooker Cloth 6X12 feet Green", url: "https://snookercart.com/buy-product/ols/products/pns-720-club-snooker-cloth-6x12-feet-green-7a68d9" },
    { name: "PNS 888 4.5X9 Green", url: "https://snookercart.com/buy-product/ols/products/pns-888-4-5x9-green-0ad74f" },
    { name: "PNS 988 Pool Cloth 4.5X9 feet Blue", url: "https://snookercart.com/buy-product/ols/products/pns-988-pool-cloth-4-5x9-feet-blue-a6e348" },
    { name: "PNS F5 Snooker Cloth 6X12 feet Green", url: "https://snookercart.com/buy-product/ols/products/pns-f5-snooker-cloth-6x12-feet-green-ed2f8f" },
    { name: "PNS F5 Strip", url: "https://snookercart.com/buy-product/ols/products/pns-f5-strip-9de608" },
    { name: "Pns Gloves Black", url: "https://snookercart.com/buy-product/ols/products/pns-gloves-black-5b269a" },
    { name: "Pns Gloves Blue", url: "https://snookercart.com/buy-product/ols/products/pns-gloves-blue-663608" },
    { name: "Pns Gloves Red", url: "https://snookercart.com/buy-product/ols/products/pns-gloves-red-bf980b" },
    { name: "Pocket Railings Pack of 6 Black", url: "https://snookercart.com/buy-product/ols/products/pocket-railings-pack-of-6-black-c04bb0" },
    { name: "Pocket Railings Pack of 6 Silver", url: "https://snookercart.com/buy-product/ols/products/pocket-railings-pack-of-6-silver-fa0c7e" },
    { name: "Pool Ball Tray", url: "https://snookercart.com/buy-product/ols/products/pool-ball-tray-1ba4b6" },
    { name: "Pool Cue Break", url: "https://snookercart.com/buy-product/ols/products/pool-cue-break-6734b8" },
    { name: "Pool Cue Break- Jump", url: "https://snookercart.com/buy-product/ols/products/pool-cue-break-jump-628f1c" },
    { name: "Pool Cue Case 4 Holes Black - White", url: "https://snookercart.com/buy-product/ols/products/pool-cue-case-4-holes-black-white-831be2" },
    { name: "Pool Cue Case 4 Holes Red - Maroon", url: "https://snookercart.com/buy-product/ols/products/pool-cue-case-4-holes-red-maroon-ddaec6" },
    { name: "Pool Cue Case 4 Holes Silver", url: "https://snookercart.com/buy-product/ols/products/pool-cue-case-4-holes-silver-14a738" },
    { name: "Pool Cue Case 6 Holes Black", url: "https://snookercart.com/buy-product/ols/products/pool-cue-case-6-holes-black-9d9ccb" },
    { name: "Pool Cue Case 9 Holes Black", url: "https://snookercart.com/buy-product/ols/products/pool-cue-case-9-holes-black-56e014" },
    { name: "Pool Cue Case 9 Holes Brown", url: "https://snookercart.com/buy-product/ols/products/pool-cue-case-9-holes-brown-054dc6" },
    { name: "Pool Cue Playing", url: "https://snookercart.com/buy-product/ols/products/pool-cue-playing-d41d33" },
    { name: "Pool Cue rest Fibre", url: "https://snookercart.com/buy-product/ols/products/pool-cue-rest-fibre-bea5c6" },
    { name: "Pool Keychains Glass Single Transparent", url: "https://snookercart.com/buy-product/ols/products/pool-keychains-glass-single-transparent-713967" },
    { name: "Pool Keychains Large Single White", url: "https://snookercart.com/buy-product/ols/products/pool-keychains-large-single-white-7a2731" },
    { name: "Pool Keychains Small Single", url: "https://snookercart.com/buy-product/ols/products/pool-keychains-small-single-f20116" },
    { name: "Pool Tip General 14mm Light Green", url: "https://snookercart.com/buy-product/ols/products/pool-tip-general-14mm-light-green-49219a" },
    { name: "Pool Tournament Ball set Baekeland", url: "https://snookercart.com/buy-product/ols/products/pool-tournament-ball-set-baekeland-96b6d2" },
    { name: "Portable Cue rest", url: "https://snookercart.com/buy-product/ols/products/portable-cue-rest-a431c4" },
    { name: "Position Market", url: "https://snookercart.com/buy-product/ols/products/position-market-54c15f" },
    { name: "Power Glide original 3/4", url: "https://snookercart.com/buy-product/ols/products/power-glide-original-3-4-9e5894" },
    { name: "Predator Chalk Single Dark Blue", url: "https://snookercart.com/buy-product/ols/products/predator-chalk-single-dark-blue-242e19" },
    { name: "Predator Gloves Black - Grey", url: "https://snookercart.com/buy-product/ols/products/predator-gloves-black-grey-d7752c" },
    { name: "Predator Gloves Black - Yellow", url: "https://snookercart.com/buy-product/ols/products/predator-gloves-black-yellow-d7588b" },
    { name: "Predator Gloves Black-Golden", url: "https://snookercart.com/buy-product/ols/products/predator-gloves-black-golden-d0d96f" },
    { name: "Predator Gloves Black-Grey", url: "https://snookercart.com/buy-product/ols/products/predator-gloves-black-grey-d91d63" },
    { name: "Predator Gloves Black-Red", url: "https://snookercart.com/buy-product/ols/products/predator-gloves-black-red-5c79f6" },
    { name: "Predator Gloves Red- Green - Black", url: "https://snookercart.com/buy-product/ols/products/predator-gloves-red-green-black-42ff9c" },
    { name: "Predator Towel", url: "https://snookercart.com/buy-product/ols/products/predator-towel-1612a7" },
    { name: "Premium Cue Case For 3 Nos Black 1 Piece", url: "https://snookercart.com/buy-product/ols/products/premium-cue-case-for-3-nos-black-1-piece-0e3801" },
    { name: "Premium Cue Case For 8 Nos Silver 1 Piece", url: "https://snookercart.com/buy-product/ols/products/premium-cue-case-for-8-nos-silver-1-piece-46f3ff" },
    { name: "Professional Chalk Single Grey", url: "https://snookercart.com/buy-product/ols/products/professional-chalk-single-grey-81cb38" },
    { name: "PRO-Tec 6X12 feet Green", url: "https://snookercart.com/buy-product/ols/products/pro-tec-6x12-feet-green-c29eea" },
    { name: "PRO-Tec 6X12 feet Green Bed", url: "https://snookercart.com/buy-product/ols/products/pro-tec-6x12-feet-green-bed-428335" },
    { name: "Railing Brush Premium", url: "https://snookercart.com/buy-product/ols/products/railing-brush-premium-e240aa" },
    { name: "Rest Head Golden Without cap", url: "https://snookercart.com/buy-product/ols/products/rest-head-golden-without-cap-c8e970" },
    { name: "Riley Club Cues 1 Piece", url: "https://snookercart.com/buy-product/ols/products/riley-club-cues-1-piece-d48e78" },
    { name: "Riley Club Cues 3/4", url: "https://snookercart.com/buy-product/ols/products/riley-club-cues-3-4-2edcb6" },
    { name: "Riley Eng Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/riley-eng-cue-3-4-f90165" },
    { name: "Riley Made in England Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/riley-made-in-england-cue-3-4-cdbb48" },
    { name: "Riley Professional Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/riley-professional-cue-3-4-0c0398" },
    { name: "Ros Towel Single Black", url: "https://snookercart.com/buy-product/ols/products/ros-towel-single-black-e25c35" },
    { name: "Round Railing Brush - 7 Inch ( Railing Brush )", url: "https://snookercart.com/buy-product/ols/products/round-railing-brush-7-inch-railing-brush-fd3b3f" },
    { name: "ROX Towel", url: "https://snookercart.com/buy-product/ols/products/rox-towel-6403d8" },
    { name: "Royal Oak Tip 10mm Brown", url: "https://snookercart.com/buy-product/ols/products/royal-oak-tip-10mm-brown-d24872" },
    { name: "Saphire Pool Ballset 52.4mm", url: "https://snookercart.com/buy-product/ols/products/saphire-pool-ballset-52-4mm-295173" },
    { name: "Sapphire Tip Med 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/sapphire-tip-med-10mm-blue-e21f86" },
    { name: "Scoreboard Digital Remote", url: "https://snookercart.com/buy-product/ols/products/scoreboard-digital-remote-5b95eb" },
    { name: "Silver Cup Chalk Single Black", url: "https://snookercart.com/buy-product/ols/products/silver-cup-chalk-single-black-995a56" },
    { name: "Silver Cup Chalk Single Purple", url: "https://snookercart.com/buy-product/ols/products/silver-cup-chalk-single-purple-305e0a" },
    { name: "Silver Cup Chalk Single Red", url: "https://snookercart.com/buy-product/ols/products/silver-cup-chalk-single-red-3b53ce" },
    { name: "Silver Cup Chalk Single White", url: "https://snookercart.com/buy-product/ols/products/silver-cup-chalk-single-white-632263" },
    { name: "SLP Pool Cue 1/2", url: "https://snookercart.com/buy-product/ols/products/slp-pool-cue-1-2-ea6afc" },
    { name: "Small Universal Extension Black", url: "https://snookercart.com/buy-product/ols/products/small-universal-extension-black-0fe7e7" },
    { name: "Small Universal Extension Black - Blue", url: "https://snookercart.com/buy-product/ols/products/small-universal-extension-black-blue-bef518" },
    { name: "Small Universal Extension Black - Gold", url: "https://snookercart.com/buy-product/ols/products/small-universal-extension-black-gold-36f697" },
    { name: "Small Universal Extension Black - Red", url: "https://snookercart.com/buy-product/ols/products/small-universal-extension-black-red-fea77f" },
    { name: "Small Universal Extension Black - Silver", url: "https://snookercart.com/buy-product/ols/products/small-universal-extension-black-silver-cebb0e" },
    { name: "Snooker Ball Tray", url: "https://snookercart.com/buy-product/ols/products/snooker-ball-tray-f24506" },
    { name: "Spider Head", url: "https://snookercart.com/buy-product/ols/products/spider-head-25b728" },
    { name: "Spider Head Xingpai", url: "https://snookercart.com/buy-product/ols/products/spider-head-xingpai-46b633" },
    { name: "SPR GL Gloves Black", url: "https://snookercart.com/buy-product/ols/products/spr-gl-gloves-black-63b846" },
    { name: "SPR GL Gloves Blue", url: "https://snookercart.com/buy-product/ols/products/spr-gl-gloves-blue-c797d7" },
    { name: "SPR GL Gloves Blue-Black", url: "https://snookercart.com/buy-product/ols/products/spr-gl-gloves-blue-black-96450f" },
    { name: "Strachan 6811 6X12 feet Green 30 Oz with Cushion", url: "https://snookercart.com/buy-product/ols/products/strachan-6811-6x12-feet-green-30-oz-with-cushion-0f4955" },
    { name: "Strachan 6811 Cloth 5X10 Cushion Set", url: "https://snookercart.com/buy-product/ols/products/strachan-6811-cloth-5x10-cushion-set-c60338" },
    { name: "Strachan 6811 Cloth 6X12 Cushion Set", url: "https://snookercart.com/buy-product/ols/products/strachan-6811-cloth-6x12-cushion-set-0bea3e" },
    { name: "Stroke Excerciser Single Black-Transparent", url: "https://snookercart.com/buy-product/ols/products/stroke-excerciser-single-black-transparent-727bd5" },
    { name: "Stroke Exerciser", url: "https://snookercart.com/buy-product/ols/products/stroke-exerciser-60554f" },
    { name: "Sunny Pro Tip (Pack of 1) 10mm Brown", url: "https://snookercart.com/buy-product/ols/products/sunny-pro-tip-pack-of-1-10mm-brown-19b02f" },
    { name: "Super Blue Diamond Gloves", url: "https://snookercart.com/buy-product/ols/products/super-blue-diamond-gloves-4acbcf" },
    { name: "Super Pool 4X8 feet Blue", url: "https://snookercart.com/buy-product/ols/products/super-pool-4x8-feet-blue-1fee3e" },
    { name: "Super Pool 4X8 feet Green", url: "https://snookercart.com/buy-product/ols/products/super-pool-4x8-feet-green-6baa26" },
    { name: "Super Pool 4X8 feet Red", url: "https://snookercart.com/buy-product/ols/products/super-pool-4x8-feet-red-9c40b0" },
    { name: "Table Brush Brown 9 Inch", url: "https://snookercart.com/buy-product/ols/products/table-brush-brown-9-inch-fa55cb" },
    { name: "Table Brush Light Brown 10.5 Inch", url: "https://snookercart.com/buy-product/ols/products/table-brush-light-brown-10-5-inch-d20ab3" },
    { name: "Table Brush Light Brown Premium - 12 Inch", url: "https://snookercart.com/buy-product/ols/products/table-brush-light-brown-premium-12-inch-23276d" },
    { name: "Table Brush Light Brown Slim - 12 Inch", url: "https://snookercart.com/buy-product/ols/products/table-brush-light-brown-slim-12-inch-f914b7" },
    { name: "Table Brush Maroon Premium Quality - 12 Inch", url: "https://snookercart.com/buy-product/ols/products/table-brush-maroon-premium-quality-12-inch-18ce56" },
    { name: "Table Brush Premium Maroon- 10 Inch", url: "https://snookercart.com/buy-product/ols/products/table-brush-premium-maroon-10-inch-6131df" },
    { name: "Table Brush Premium Quality Maroon - 8 Inch ( Railing Brush )", url: "https://snookercart.com/buy-product/ols/products/table-brush-premium-quality-maroon-8-inch-railing-brush-b9bac8" },
    { name: "Table Heater", url: "https://snookercart.com/buy-product/ols/products/table-heater-217505" },
    { name: "Table Rest Hooks Pack of 6 Golden", url: "https://snookercart.com/buy-product/ols/products/table-rest-hooks-pack-of-6-golden-f2c3c5" },
    { name: "Taiwan Tip 10mm Brown", url: "https://snookercart.com/buy-product/ols/products/taiwan-tip-10mm-brown-675f87" },
    { name: "Talisman Pro Tip 10mm Brown", url: "https://snookercart.com/buy-product/ols/products/talisman-pro-tip-10mm-brown-a60a24" },
    { name: "Talisman Tip Hard WB 10mm Green", url: "https://snookercart.com/buy-product/ols/products/talisman-tip-hard-wb-10mm-green-540083" },
    { name: "Talisman Trinity Tip 10mm Grey", url: "https://snookercart.com/buy-product/ols/products/talisman-trinity-tip-10mm-grey-3f65c7" },
    { name: "Taom 2.0 Chalk Single Green", url: "https://snookercart.com/buy-product/ols/products/taom-2-0-chalk-single-green-3fda43" },
    { name: "Taom 2.0 Chalk Single Grey", url: "https://snookercart.com/buy-product/ols/products/taom-2-0-chalk-single-grey-a85fc4" },
    { name: "Taom Cap Black", url: "https://snookercart.com/buy-product/ols/products/taom-cap-black-7f4de0" },
    { name: "Taom Chalk Pouch without Magnet", url: "https://snookercart.com/buy-product/ols/products/taom-chalk-pouch-without-magnet-e016b0" },
    { name: "Taom Fusion Tip 10mm Blue", url: "https://snookercart.com/buy-product/ols/products/taom-fusion-tip-10mm-blue-3aaab9" },
    { name: "Taom Fusion Tip 14mm Blue", url: "https://snookercart.com/buy-product/ols/products/taom-fusion-tip-14mm-blue-6cd192" },
    { name: "Taom Gloves Black Left Large", url: "https://snookercart.com/buy-product/ols/products/taom-gloves-black-left-large-5d3034" },
    { name: "Taom Gloves Black Left Medium", url: "https://snookercart.com/buy-product/ols/products/taom-gloves-black-left-medium-78b241" },
    { name: "Taom Gloves Black Left Small", url: "https://snookercart.com/buy-product/ols/products/taom-gloves-black-left-small-195540" },
    { name: "Taom Gloves Black Right Large", url: "https://snookercart.com/buy-product/ols/products/taom-gloves-black-right-large-a47571" },
    { name: "Taom Gloves Black Right Medium", url: "https://snookercart.com/buy-product/ols/products/taom-gloves-black-right-medium-e1ed3d" },
    { name: "Taom Magnetic Chalk Holder", url: "https://snookercart.com/buy-product/ols/products/taom-magnetic-chalk-holder-239c3d" },
    { name: "Taom Official Batch", url: "https://snookercart.com/buy-product/ols/products/taom-official-batch-2a5a5b" },
    { name: "Taom Pro Tip 10mm Black", url: "https://snookercart.com/buy-product/ols/products/taom-pro-tip-10mm-black-d1b552" },
    { name: "Taom Pro Tip 14mm Black", url: "https://snookercart.com/buy-product/ols/products/taom-pro-tip-14mm-black-bb12dd" },
    { name: "Taom Pyro Chalk Single Blue", url: "https://snookercart.com/buy-product/ols/products/taom-pyro-chalk-single-blue-0f274f" },
    { name: "Taom Towel Single", url: "https://snookercart.com/buy-product/ols/products/taom-towel-single-bf3007" },
    { name: "Taom V10 Batch", url: "https://snookercart.com/buy-product/ols/products/taom-v10-batch-c27c2f" },
    { name: "Taom V10 Chalk Pack of 9 Blue", url: "https://snookercart.com/buy-product/ols/products/taom-v10-chalk-pack-of-9-blue-b5df3e" },
    { name: "Taom V10 Chalk Single Blue", url: "https://snookercart.com/buy-product/ols/products/taom-v10-chalk-single-blue-666a3c" },
    { name: "Taom V10 Chalk Single Green", url: "https://snookercart.com/buy-product/ols/products/taom-v10-chalk-single-green-7c6d32" },
    { name: "Taom V10 Green Cap", url: "https://snookercart.com/buy-product/ols/products/taom-v10-green-cap-50ff6e" },
    { name: "Telescopic Extension Aluminium Black - Gold 12 Inch", url: "https://snookercart.com/buy-product/ols/products/telescopic-extension-aluminium-black-gold-12-inch-c62edc" },
    { name: "Telescopic Extension Aluminium Black - Silver 12 Inch", url: "https://snookercart.com/buy-product/ols/products/telescopic-extension-aluminium-black-silver-12-inch-53c3d6" },
    { name: "Telescopic Extension Aluminium Black 12 Inch", url: "https://snookercart.com/buy-product/ols/products/telescopic-extension-aluminium-black-12-inch-195c61" },
    { name: "Telescopic Extension Aluminium Black-Blue 12 Inch", url: "https://snookercart.com/buy-product/ols/products/telescopic-extension-aluminium-black-blue-12-inch-018d25" },
    { name: "Tip protector rubber 10mm", url: "https://snookercart.com/buy-product/ols/products/tip-protector-rubber-10mm-c18214" },
    { name: "Tip protector rubber 12mm", url: "https://snookercart.com/buy-product/ols/products/tip-protector-rubber-12mm-d5e9c5" },
    { name: "Tip Puncture Brown 2 Inch Double Sided", url: "https://snookercart.com/buy-product/ols/products/tip-puncture-brown-2-inch-double-sided-19c65e" },
    { name: "Tip shaper round", url: "https://snookercart.com/buy-product/ols/products/tip-shaper-round-73bb77" },
    { name: "Tip Sharpner", url: "https://snookercart.com/buy-product/ols/products/tip-sharpner-ccc4ee" },
    { name: "Toam Black Racking Cloth", url: "https://snookercart.com/buy-product/ols/products/toam-black-racking-cloth-770c33" },
    { name: "Toam Green Racking Cloth", url: "https://snookercart.com/buy-product/ols/products/toam-green-racking-cloth-bdade8" },
    { name: "Training Cue Ball", url: "https://snookercart.com/buy-product/ols/products/training-cue-ball-a3c42e" },
    { name: "Triangle Chalk Club Pack of 144 Blue", url: "https://snookercart.com/buy-product/ols/products/triangle-chalk-club-pack-of-144-blue-f818d4" },
    { name: "Triangle Chalk Club Pack of 144 Spruce", url: "https://snookercart.com/buy-product/ols/products/triangle-chalk-club-pack-of-144-spruce-3c5d52" },
    { name: "Triangle Chalk Pack of 12 Blue", url: "https://snookercart.com/buy-product/ols/products/triangle-chalk-pack-of-12-blue-4b3d79" },
    { name: "Triangle Chalk Single Light Green", url: "https://snookercart.com/buy-product/ols/products/triangle-chalk-single-light-green-40da2c" },
    { name: "Trianle Pro Chalk Pack of 12 Dark Green", url: "https://snookercart.com/buy-product/ols/products/trianle-pro-chalk-pack-of-12-dark-green-756aae" },
    { name: "Trianle Pro Chalk Single Dark Green", url: "https://snookercart.com/buy-product/ols/products/trianle-pro-chalk-single-dark-green-0c2411" },
    { name: "Trianle Pro Chalk Single Light Green", url: "https://snookercart.com/buy-product/ols/products/trianle-pro-chalk-single-light-green-d3fdcc" },
    { name: "Tube case plain Black 1/2", url: "https://snookercart.com/buy-product/ols/products/tube-case-plain-black-1-2-0bfb7e" },
    { name: "Tube case plain Black 3/4", url: "https://snookercart.com/buy-product/ols/products/tube-case-plain-black-3-4-11cc64" },
    { name: "Unicues American Pool Ballset", url: "https://snookercart.com/buy-product/ols/products/unicues-american-pool-ballset-c08c3a" },
    { name: "Unicues Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/unicues-cue-1-piece-579a4d" },
    { name: "Universal Telescopic Extension Blue - Black", url: "https://snookercart.com/buy-product/ols/products/universal-telescopic-extension-blue-black-86138a" },
    { name: "Upper Pocket Set Pack of 6 Black", url: "https://snookercart.com/buy-product/ols/products/upper-pocket-set-pack-of-6-black-4ed0ec" },
    { name: "Upper Pocket Set Pack of 6 Brown", url: "https://snookercart.com/buy-product/ols/products/upper-pocket-set-pack-of-6-brown-ec527e" },
    { name: "Upper Pocket Set Pack of 6 Cherry Red", url: "https://snookercart.com/buy-product/ols/products/upper-pocket-set-pack-of-6-cherry-red-094f15" },
    { name: "Upper Pocket Set Pack of 6 Dark Brown", url: "https://snookercart.com/buy-product/ols/products/upper-pocket-set-pack-of-6-dark-brown-4842b9" },
    { name: "Upper Pocket Set Pack of 6 Light Brown", url: "https://snookercart.com/buy-product/ols/products/upper-pocket-set-pack-of-6-light-brown-f3fd50" },
    { name: "Upper Pocket Set Pack of 6 White", url: "https://snookercart.com/buy-product/ols/products/upper-pocket-set-pack-of-6-white-78e65a" },
    { name: "Used Pro-Tech Cloth 6X12 feet Green Bed", url: "https://snookercart.com/buy-product/ols/products/used-pro-tech-cloth-6x12-feet-green-bed-baa270" },
    { name: "Vip Pro Tip 10mm Black", url: "https://snookercart.com/buy-product/ols/products/vip-pro-tip-10mm-black-6a58cd" },
    { name: "Volkan Cue Cleaner 20ml", url: "https://snookercart.com/buy-product/ols/products/volkan-cue-cleaner-20ml-f35996" },
    { name: "Volkan Wax 20gm", url: "https://snookercart.com/buy-product/ols/products/volkan-wax-20gm-c66bb3" },
    { name: "Wall Cue Stand Wooden", url: "https://snookercart.com/buy-product/ols/products/wall-cue-stand-wooden-82750d" },
    { name: "Wall Cue Stand Wooden Premium", url: "https://snookercart.com/buy-product/ols/products/wall-cue-stand-wooden-premium-65c0f4" },
    { name: "Wanstan Chalk Single Blue", url: "https://snookercart.com/buy-product/ols/products/wanstan-chalk-single-blue-4faad2" },
    { name: "Whirl Wind Chalk Single Dark Green", url: "https://snookercart.com/buy-product/ols/products/whirl-wind-chalk-single-dark-green-f4cab8" },
    { name: "Wiraka 6565 5X10 feet Green B", url: "https://snookercart.com/buy-product/ols/products/wiraka-6565-5x10-feet-green-b-e066b5" },
    { name: "Wiraka 777 4X8 feet Green B", url: "https://snookercart.com/buy-product/ols/products/wiraka-777-4x8-feet-green-b-f637bd" },
    { name: "Wiraka 777 4X8 feet Green OG", url: "https://snookercart.com/buy-product/ols/products/wiraka-777-4x8-feet-green-og-ba464c" },
    { name: "Wiraka 777 5X10 feet Green B BED", url: "https://snookercart.com/buy-product/ols/products/wiraka-777-5x10-feet-green-b-bed-6419f8" },
    { name: "Wiraka Chalk Single Light Green", url: "https://snookercart.com/buy-product/ols/products/wiraka-chalk-single-light-green-9945db" },
    { name: "Wiraka Pro 960 4.5X9 feet Blue", url: "https://snookercart.com/buy-product/ols/products/wiraka-pro-960-4-5x9-feet-blue-da3046" },
    { name: "Wiraka Pro 960 4X8 feet Blue", url: "https://snookercart.com/buy-product/ols/products/wiraka-pro-960-4x8-feet-blue-add465" },
    { name: "Wooden rest Stick Black", url: "https://snookercart.com/buy-product/ols/products/wooden-rest-stick-black-40f99c" },
    { name: "Wooden rest Stick Black Larger", url: "https://snookercart.com/buy-product/ols/products/wooden-rest-stick-black-larger-ffac8b" },
    { name: "Wooden rest Stick Yellow", url: "https://snookercart.com/buy-product/ols/products/wooden-rest-stick-yellow-077841" },
    { name: "Wooden rest Stick Yellow Larger", url: "https://snookercart.com/buy-product/ols/products/wooden-rest-stick-yellow-larger-ff239e" },
    { name: "Wooden Score Board Brown", url: "https://snookercart.com/buy-product/ols/products/wooden-score-board-brown-97dbf9" },
    { name: "Wooden Tip Compressor", url: "https://snookercart.com/buy-product/ols/products/wooden-tip-compressor-4860f9" },
    { name: "Woods Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/woods-cue-3-4-b2161e" },
    { name: "Xiguan Ball Cleaner", url: "https://snookercart.com/buy-product/ols/products/xiguan-ball-cleaner-84009c" },
    { name: "Xiguan Fabric Softnerer", url: "https://snookercart.com/buy-product/ols/products/xiguan-fabric-softnerer-0e4067" },
    { name: "Xiguan Pro Pool Tip 14mm Black", url: "https://snookercart.com/buy-product/ols/products/xiguan-pro-pool-tip-14mm-black-274ab8" },
    { name: "Xing Kang 8A TV Pro Cup Ballset ( Snooker)", url: "https://snookercart.com/buy-product/ols/products/xing-kang-8a-tv-pro-cup-ballset-snooker-1e9a5a" },
    { name: "Xing Kang Ball set", url: "https://snookercart.com/buy-product/ols/products/xing-kang-ball-set-ec3191" },
    { name: "Xingpai American Pool Cue 1/2", url: "https://snookercart.com/buy-product/ols/products/xingpai-american-pool-cue-1-2-ad191d" },
    { name: "Xingpai American Pool Cue 3 Piece", url: "https://snookercart.com/buy-product/ols/products/xingpai-american-pool-cue-3-piece-5b0708" },
    { name: "Xingpai Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/xingpai-cue-3-4-46e13e" },
    { name: "Xingpai Leather Case Black -White 3/4", url: "https://snookercart.com/buy-product/ols/products/xingpai-leather-case-black-white-3-4-3a0d73" },
    { name: "Xingpai Leather for Inner Pocket Pack of 6", url: "https://snookercart.com/buy-product/ols/products/xingpai-leather-for-inner-pocket-pack-of-6-f703dc" },
    { name: "Xingpai railing Pack of 6 Black-Golden - Small", url: "https://snookercart.com/buy-product/ols/products/xingpai-railing-pack-of-6-black-golden-small-84b266" },
    { name: "Apex 147 White Perfect Badge Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/apex-147-white-perfect-badge-cue-1-piece-4420ac" },
    { name: "Apex Classic Cue 1", url: "https://snookercart.com/buy-product/ols/products/apex-classic-cue-1-ee5f6e" },
    { name: "Apex Merchant Cue 1", url: "https://snookercart.com/buy-product/ols/products/apex-merchant-cue-1-657adf" },
    { name: "Apex Merchant Cue 2", url: "https://snookercart.com/buy-product/ols/products/apex-merchant-cue-2-76be2d" },
    { name: "Apex Merchant Cue 3", url: "https://snookercart.com/buy-product/ols/products/apex-merchant-cue-3-1c09b0" },
    { name: "Apex Perfect Cue 1", url: "https://snookercart.com/buy-product/ols/products/apex-perfect-cue-1-255cea" },
    { name: "Apex Perfect Cue 2", url: "https://snookercart.com/buy-product/ols/products/apex-perfect-cue-2-e8a784" },
    { name: "Apex Rocket Cue 1", url: "https://snookercart.com/buy-product/ols/products/apex-rocket-cue-1-4f322b" },
    { name: "Apex Ultimate Cue 1", url: "https://snookercart.com/buy-product/ols/products/apex-ultimate-cue-1-4925ef" },
    { name: "Apex Ultimate Cue 2", url: "https://snookercart.com/buy-product/ols/products/apex-ultimate-cue-2-c2e61c" },
    { name: "Apex Ultimate Cue 3", url: "https://snookercart.com/buy-product/ols/products/apex-ultimate-cue-3-251692" },
    { name: "Apex Ultimate Cue 4", url: "https://snookercart.com/buy-product/ols/products/apex-ultimate-cue-4-2b60e3" },
    { name: "Apex Ultimate Cue 5", url: "https://snookercart.com/buy-product/ols/products/apex-ultimate-cue-5-5546af" },
    { name: "Apex Ultimate Cue 6", url: "https://snookercart.com/buy-product/ols/products/apex-ultimate-cue-6-030907" },
    { name: "Apex Ultimate Cue 7", url: "https://snookercart.com/buy-product/ols/products/apex-ultimate-cue-7-ce98a1" },
    { name: "Apex Ultimate Cue 8", url: "https://snookercart.com/buy-product/ols/products/apex-ultimate-cue-8-0325c8" },
    { name: "Arrow Master Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/arrow-master-cue-3-4-1213da" },
    { name: "Arrow Master Cue 3/4 (001)", url: "https://snookercart.com/buy-product/ols/products/arrow-master-cue-3-4-001-665708" },
    { name: "Avatar Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/avatar-cue-1-piece-0864c0" },
    { name: "Avatar Cue 1 Piece (001)", url: "https://snookercart.com/buy-product/ols/products/avatar-cue-1-piece-001-06977d" },
    { name: "Black Chinese Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/black-chinese-cue-1-piece-b960dc" },
    { name: "Bliston Cue 1", url: "https://snookercart.com/buy-product/ols/products/bliston-cue-1-3d1cef" },
    { name: "Bridge Cue 1/2", url: "https://snookercart.com/buy-product/ols/products/bridge-cue-1-2-22a470" },
    { name: "Chinese Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/chinese-cue-1-piece-7a0e41" },
    { name: "Chinese Cue 1 Piece (001)", url: "https://snookercart.com/buy-product/ols/products/chinese-cue-1-piece-001-0658e6" },
    { name: "Ebony Hunter Cue 1", url: "https://snookercart.com/buy-product/ols/products/ebony-hunter-cue-1-11134a" },
    { name: "Janeson Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/janeson-cue-3-4-61b955" },
    { name: "LP 1 Piece", url: "https://snookercart.com/buy-product/ols/products/lp-1-piece-e2e45a" },
    { name: "Lp Black Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/lp-black-cue-3-4-8a5ed1" },
    { name: "LP Classic Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/lp-classic-cue-3-4-ec5645" },
    { name: "Lp Loppy Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/lp-loppy-cue-3-4-c2400c" },
    { name: "Maximus Legend Plus Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/maximus-legend-plus-cue-1-piece-aecf43" },
    { name: "Maximus Precious Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/maximus-precious-cue-1-piece-3d2540" },
    { name: "Maximus Premium Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/maximus-premium-cue-1-piece-3b3313" },
    { name: "Maximus Premium Cue 1 Piece (001)", url: "https://snookercart.com/buy-product/ols/products/maximus-premium-cue-1-piece-001-c948f8" },
    { name: "Maximus Premium Cue 1 Piece (002)", url: "https://snookercart.com/buy-product/ols/products/maximus-premium-cue-1-piece-002-04b230" },
    { name: "Maximus Premium Cue 1 Piece (003)", url: "https://snookercart.com/buy-product/ols/products/maximus-premium-cue-1-piece-003-5ad74d" },
    { name: "Omin Basic Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/omin-basic-cue-1-piece-39c6a5" },
    { name: "Omin Basic Cue 1 Piece (001)", url: "https://snookercart.com/buy-product/ols/products/omin-basic-cue-1-piece-001-4953d0" },
    { name: "Omin Basic Cue 1 Piece (002)", url: "https://snookercart.com/buy-product/ols/products/omin-basic-cue-1-piece-002-90fa1d" },
    { name: "Omin Basic Cue 1 Piece (003)", url: "https://snookercart.com/buy-product/ols/products/omin-basic-cue-1-piece-003-92a058" },
    { name: "Omin Basic Cue 1 Piece (004)", url: "https://snookercart.com/buy-product/ols/products/omin-basic-cue-1-piece-004-8f6504" },
    { name: "Omin Champion Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/omin-champion-cue-1-piece-d7277a" },
    { name: "Omin Champion Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/omin-champion-cue-3-4-c33552" },
    { name: "Omin Classic Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/omin-classic-cue-1-piece-30ff96" },
    { name: "Omin Classic Cue 1 Piece (001)", url: "https://snookercart.com/buy-product/ols/products/omin-classic-cue-1-piece-001-b2a2d4" },
    { name: "Omin Imagine Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/omin-imagine-cue-1-piece-42742b" },
    { name: "Omin Master Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/omin-master-cue-1-piece-4252a1" },
    { name: "Omin Master Cue 1 Piece (001)", url: "https://snookercart.com/buy-product/ols/products/omin-master-cue-1-piece-001-b6ccb0" },
    { name: "Omin Master Cue 1 Piece (002)", url: "https://snookercart.com/buy-product/ols/products/omin-master-cue-1-piece-002-16c008" },
    { name: "Omin Maximum 147 Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/omin-maximum-147-cue-3-4-d0f31d" },
    { name: "Omin Maximum 147 Gold Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/omin-maximum-147-gold-cue-3-4-ea8037" },
    { name: "Omin Maximum 147 Gold Cue 3/4 (001)", url: "https://snookercart.com/buy-product/ols/products/omin-maximum-147-gold-cue-3-4-001-308c94" },
    { name: "Omin Maximum 147 Gold Cue 3/4 (002)", url: "https://snookercart.com/buy-product/ols/products/omin-maximum-147-gold-cue-3-4-002-25cddf" },
    { name: "Omin O'Millenium Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/omin-o-millenium-cue-1-piece-cece2a" },
    { name: "Omin O'Millenium Cue 1 Piece (001)", url: "https://snookercart.com/buy-product/ols/products/omin-o-millenium-cue-1-piece-001-b25777" },
    { name: "Omin O'Millenium Cue 2", url: "https://snookercart.com/buy-product/ols/products/omin-o-millenium-cue-2-a768d3" },
    { name: "Omin O'Millenium Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/omin-o-millenium-cue-3-4-a9c834" },
    { name: "Omin Perfect Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/omin-perfect-cue-3-4-008054" },
    { name: "Omin Perfect Cue 3/4 (001)", url: "https://snookercart.com/buy-product/ols/products/omin-perfect-cue-3-4-001-ffc3e5" },
    { name: "Omin Perfect Cue 3/4 (002)", url: "https://snookercart.com/buy-product/ols/products/omin-perfect-cue-3-4-002-30bb3f" },
    { name: "Omin Perfect Cue 3/4 (003)", url: "https://snookercart.com/buy-product/ols/products/omin-perfect-cue-3-4-003-6437d5" },
    { name: "Omin Perfect Cue 3/4 (004)", url: "https://snookercart.com/buy-product/ols/products/omin-perfect-cue-3-4-004-46513f" },
    { name: "Omin Perfect Cue 3/4 (005)", url: "https://snookercart.com/buy-product/ols/products/omin-perfect-cue-3-4-005-061749" },
    { name: "Omin Professional Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/omin-professional-cue-1-piece-dd599f" },
    { name: "Omin Professional Cue 1 Piece (001)", url: "https://snookercart.com/buy-product/ols/products/omin-professional-cue-1-piece-001-e9b23f" },
    { name: "Omin Professional Cue 1 Piece (002)", url: "https://snookercart.com/buy-product/ols/products/omin-professional-cue-1-piece-002-fbc0b8" },
    { name: "Omin Professional Cue 1 Piece (003)", url: "https://snookercart.com/buy-product/ols/products/omin-professional-cue-1-piece-003-87e7c9" },
    { name: "Omin Professional Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/omin-professional-cue-3-4-b63363" },
    { name: "Omin Professional Cue 3/4 (001)", url: "https://snookercart.com/buy-product/ols/products/omin-professional-cue-3-4-001-d0317a" },
    { name: "Omin Ultimate Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/omin-ultimate-cue-1-piece-157bd9" },
    { name: "Omin Ultimate Cue 1 Piece (001)", url: "https://snookercart.com/buy-product/ols/products/omin-ultimate-cue-1-piece-001-faca87" },
    { name: "Omin Ultimate Cue 1 Piece (002)", url: "https://snookercart.com/buy-product/ols/products/omin-ultimate-cue-1-piece-002-fc9af6" },
    { name: "Omin Ultimate Cue 1 Piece (003)", url: "https://snookercart.com/buy-product/ols/products/omin-ultimate-cue-1-piece-003-8a650b" },
    { name: "Omin Ultimate Cue 1 Piece (004)", url: "https://snookercart.com/buy-product/ols/products/omin-ultimate-cue-1-piece-004-0b9b44" },
    { name: "Pheonix Elite 1/2", url: "https://snookercart.com/buy-product/ols/products/pheonix-elite-1-2-17ab68" },
    { name: "Phoenix Unity Cue 1 Piece (001)", url: "https://snookercart.com/buy-product/ols/products/phoenix-unity-cue-1-piece-001-403e37" },
    { name: "Slp Cue 3/4", url: "https://snookercart.com/buy-product/ols/products/slp-cue-3-4-fdc1dd" },
    { name: "Uni Cues 3/4", url: "https://snookercart.com/buy-product/ols/products/uni-cues-3-4-b00998" },
    { name: "Omin Tip Puncture Black Single Sided", url: "https://snookercart.com/buy-product/ols/products/omin-tip-puncture-black-single-sided-7a1dcd" },
    { name: "Omin Tip Puncture Blue Single Sided", url: "https://snookercart.com/buy-product/ols/products/omin-tip-puncture-blue-single-sided-c94f77" },
    { name: "Omin Tip Puncture Golden Single Sided", url: "https://snookercart.com/buy-product/ols/products/omin-tip-puncture-golden-single-sided-bc165b" },
    { name: "Omin Tip Puncture Light Blue Single Sided", url: "https://snookercart.com/buy-product/ols/products/omin-tip-puncture-light-blue-single-sided-fecf06" },
    { name: "Omin Tip Puncture Navy Blue Single Sided", url: "https://snookercart.com/buy-product/ols/products/omin-tip-puncture-navy-blue-single-sided-8a0443" },
    { name: "Omin Tip Puncture Purple Single Sided", url: "https://snookercart.com/buy-product/ols/products/omin-tip-puncture-purple-single-sided-31cd3e" },
    { name: "Omin Tip Puncture Red Single Sided", url: "https://snookercart.com/buy-product/ols/products/omin-tip-puncture-red-single-sided-60411e" },
    { name: "Omin Tip Puncture Silver Single Sided", url: "https://snookercart.com/buy-product/ols/products/omin-tip-puncture-silver-single-sided-d55708" },
    { name: "Phoenix Unity Cue 1 Piece", url: "https://snookercart.com/buy-product/ols/products/phoenix-unity-cue-1-piece-4e2a19" },
    { name: "Tip Puncture Black Double Sided", url: "https://snookercart.com/buy-product/ols/products/tip-puncture-black-double-sided-76bc98" },
    { name: "Tip Puncture Dark Golden 2 Inch Double Sided", url: "https://snookercart.com/buy-product/ols/products/tip-puncture-dark-golden-2-inch-double-sided-681572" },
    { name: "Tip Puncture Golden 2 Inch Double Sided", url: "https://snookercart.com/buy-product/ols/products/tip-puncture-golden-2-inch-double-sided-370729" },
    { name: "Tip Puncture Golden Double Sided", url: "https://snookercart.com/buy-product/ols/products/tip-puncture-golden-double-sided-da6f6c" },
    { name: "Tip Puncture Red 2 Inch Double Sided", url: "https://snookercart.com/buy-product/ols/products/tip-puncture-red-2-inch-double-sided-288c94" },
    { name: "Tip Puncture Red 2 Inch Single Sided", url: "https://snookercart.com/buy-product/ols/products/tip-puncture-red-2-inch-single-sided-834ccf" },
    { name: "Tip Puncture Red Double Sided", url: "https://snookercart.com/buy-product/ols/products/tip-puncture-red-double-sided-73d4fa" },
    { name: "Tip Puncture Silver 2 Inch Single Sided", url: "https://snookercart.com/buy-product/ols/products/tip-puncture-silver-2-inch-single-sided-d7d011" },
    { name: "Tip Puncture Silver Double Sided", url: "https://snookercart.com/buy-product/ols/products/tip-puncture-silver-double-sided-311639" }
];

function searchProducts() {
    const input = document.getElementById('searchBox').value.toLowerCase();
    const suggestionBox = document.getElementById('suggestions');
    suggestionBox.innerHTML = '';

    if (input.length === 0) return;

    const filtered = products.filter(p => p.name.toLowerCase().includes(input));

    if (filtered.length === 0) {
        const li = document.createElement('li');
        li.textContent = 'No matching products found.';
        li.style.padding = '8px';
        li.style.color = 'gray';
        suggestionBox.appendChild(li);
        return;
    }

    filtered.forEach(p => {
        const li = document.createElement('li');
        li.innerHTML = `<a href="${p.url}" target="_blank" rel="noopener noreferrer" style="color: chocolate; text-decoration: none; display: block; padding: 8px;">${p.name}</a>`;
        suggestionBox.appendChild(li);
    });
}
